### ISSUE TITLE
undefined method `bytesize'

### ISSUE THREAD

**Issue by jonhue** [eval/rack-pjax#33]
I am getting the following error:

```
NoMethodError - undefined method `bytesize' for #<Rack::Pjax:0x7376760>:
  rack-pjax (1.0.0) lib/rack/pjax.rb:37:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (5.1.0.rc1) lib/active_record/migration.rb:556:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
  activesupport (5.1.0.rc1) lib/active_support/callbacks.rb:97:in `run_callbacks'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  web-console (3.5.0) lib/web_console/middleware.rb:135:in `call_app'
  web-console (3.5.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.5.0) lib/web_console/middleware.rb:18:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (5.1.0.rc1) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.1.0.rc1) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.1.0.rc1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.1.0.rc1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.1.0.rc1) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.1.0.rc1) lib/rails/rack/logger.rb:24:in `call'
  ahoy_matey (1.5.5) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activesupport (5.1.0.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (5.1.0.rc1) lib/action_dispatch/middleware/static.rb:125:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  sentry-raven (2.4.0) lib/raven/integrations/rack.rb:50:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (5.1.0.rc1) lib/rails/engine.rb:522:in `call'
  newrelic_rpm (4.0.0.332) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  puma (3.8.2) lib/puma/configuration.rb:224:in `call'
  puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
  puma (3.8.2) lib/puma/server.rb:435:in `process_client'
  puma (3.8.2) lib/puma/server.rb:299:in `block in run'
  puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mbajur** [comment]
PR #32 resolves it

**Comment by jonhue** [comment]
@mbajur has it not been included in a release on rubygems yet?

**Comment by mbajur** [comment]
I think not, this PR is not merged yet.

**Comment by jonhue** [comment]
@mbajur Oh, my bad :)

**Comment by coorasse** [comment]
What about releasing a new version with this patch, so we don't have to point to the master branch?
